name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Equal
        id: diff1
        uses: ./
        with:
          first: '{"foo": "bar"}'
          second: '{"foo": "bar"}'

      - name: Different
        id: diff2
        uses: ./
        with:
          first: '{"foo": "bar"}'
          second: '{"foo": "zoo"}'

      - name: Different2
        id: diff3
        uses: ./
        with:
          first: '{"foo": "bar", "zoo": 1}'
          second: '{"foo": "zoo", "zoo": 2}'

      - name: Output
        run: |
          echo "Equal: ${{ steps.diff1.outputs.diff}}"
          echo "Different: ${{ steps.diff2.outputs.diff}}"
          echo "Different2: ${{ steps.diff3.outputs.diff}}"
